### ISSUE TITLE
Sp2 Bulk Upload API returns Error: No handler was ready to authenticate.

### ISSUE THREAD

**Issue by tkiethanom** [oyiptong/splice#191]
@ncloudioj is this an environment issue?

This is the JSON response

```
{
 "message": "Error: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials" 
}
```

API console log
```
2015-11-03 16:44:29,870 INFO    Traceback (most recent call last):
  File "/home/tbg/domains/mozilla-splice/splice/splice/web/api/tile_upload.py", line 47, in bulk_upload
    insert_ingested_assets(ingested_assets, campaign_id, channel_id, creative_map)
  File "/home/tbg/domains/mozilla-splice/splice/splice/web/api/tile_upload.py", line 61, in insert_ingested_assets
    bucket, headers = setup_s3()
  File "/home/tbg/domains/mozilla-splice/splice/splice/web/api/tile_upload.py", line 76, in setup_s3
    bucket = Environment.instance().s3.get_bucket(Environment.instance().config.S3["bucket"])
  File "/home/tbg/domains/mozilla-splice/splice/splice/environment.py", line 113, in s3
    self.__s3_conn = boto.connect_s3()
  File "/home/tbg/domains/mozilla-splice/splice/splice-env/lib/python2.7/site-packages/boto/__init__.py", line 141, in connect_s3
    return S3Connection(aws_access_key_id, aws_secret_access_key, **kwargs)
  File "/home/tbg/domains/mozilla-splice/splice/splice-env/lib/python2.7/site-packages/boto/s3/connection.py", line 190, in __init__
    validate_certs=validate_certs, profile_name=profile_name)
  File "/home/tbg/domains/mozilla-splice/splice/splice-env/lib/python2.7/site-packages/boto/connection.py", line 568, in __init__
    host, config, self.provider, self._required_auth_capability())
  File "/home/tbg/domains/mozilla-splice/splice/splice-env/lib/python2.7/site-packages/boto/auth.py", line 939, in get_auth_handler
    'Check your credentials' % (len(names), str(names)))
NoAuthHandlerFound: No handler was ready to authenticate. 1 handlers were checked. ['HmacAuthV1Handler'] Check your credentials
```

**Comment by tkiethanom** [comment]
Google tells me this is an issue with auth to amazon S3?

**Comment by ncloudioj** [comment]
@tkiethanom you'll need the S3 credentials to run that on your machine. Have to ask our ops folks to help you out. Will keep you updated.

**Comment by tkiethanom** [comment]
Thanks for the quick reply!

**Comment by ncloudioj** [comment]
No problem, let's fix this tomorrow.

**Comment by tkiethanom** [comment]
Yea I didn't expect you to reply right away I just wanted to create the bug tonight.

**Comment by ncloudioj** [comment]
Hi @tkiethanom, my colleague @oyiptong has created S3 credentials for you. Just ping him on IRC, he will help you out there.
